name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y npm
        sudo apt-get install -y bootstrap
        sudo apt-get install -y ejs
        sudo apt-get install -y express
        sudo apt-get install -y morgan
        sudo apt-get install -y vue
        sudo apt-get install -y vue-resource


    - name: Run tests
      run: |
        npm test -- --coverage --coverageReporters=json-summary