name: coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        npm install

    - name: Run tests
      run: |
        npm test -- --coverage --coverageReporters=json-summary